### ISSUE TITLE
「大屏」年龄显示错误，配置为1993年，显示值却是72岁

### ISSUE THREAD

**Issue by zealotCE** [BRCIOT/unicorn#13]
1. 我发现大屏中所有账户的年龄都偏大，范围在60~70岁为主。
2. 在配置中创建了1993年的用户年龄显示却是72岁。
![827544373917144499](https://user-images.githubusercontent.com/26129403/41334668-05d78df0-6f19-11e8-9da7-1db44eb835f0.jpg)

**Comment by zealotCE** [comment]
原因已经找到，是由于之前代码中写死了年龄和身高，造成的错误。等待开发改成并上线。

**Comment by JerryCui** [comment]
已经修改
