### ISSUE TITLE
「大屏」优化建议：无电阻值提示与用户选择重叠。

### ISSUE THREAD

**Issue by zealotCE** [BRCIOT/unicorn#14]
无电阻提示与用户切换的弹窗重叠了。
建议修改（二选一）：
1. 调整 无电阻提示的位置
2. 将用户切换弹窗添加一个底色，而不再是透明。

重现步骤：
1. 当称体重测不到电阻时，大屏会以红字提示。
2. 点开用户切换按钮

![306120896446612061](https://user-images.githubusercontent.com/26129403/41334758-44206abe-6f19-11e8-83c7-8b991819122e.jpg)

**Comment by JerryCui** [comment]
已经修改
