### ISSUE TITLE
管理后台 500错误

### ISSUE THREAD

**Issue by zealotCE** [BRCIOT/unicorn#2]
在三处地方都会发生错误
1. 「会员管理-会员列表」
2. 「健康管理-会员列表」
3. 「健康管理-会员列表-查看详情」
![image](https://user-images.githubusercontent.com/26129403/41325658-112a57f8-6eee-11e8-8491-7597e88f6a97.png)

**Comment by taoqianbao** [comment]
fixed - the gateway was killed.
