### ISSUE TITLE
「大屏」添加用户-输入『用户名』时，看不到输入

### ISSUE THREAD

**Issue by zealotCE** [BRCIOT/unicorn#8]
原因应该是由于输入框内文字颜色与背景一致导致看不到问题。
如图
![2](https://user-images.githubusercontent.com/26129403/41327521-67380aca-6ef6-11e8-8b32-961cd98f0306.png)

建议把文字改为白色。

**Comment by zealotCE** [comment]
文字颜色目前已经改为绿色，但是文字过于偏左（与输入框太近了），建议加保持点距离

![_20180613143604](https://user-images.githubusercontent.com/26129403/41334216-56933426-6f17-11e8-8639-662891643ec6.jpg)

**Comment by JerryCui** [comment]
已经修改
